//
// Created by Dell on 2. 11. 2021.
//

#ifndef CUBICGRAPHKASZONYIFUNCTIONPROGRAM_ENUMS_H
#define CUBICGRAPHKASZONYIFUNCTIONPROGRAM_ENUMS_H

enum append{
    APPEND,
    NO_APPEND
};

#endif //CUBICGRAPHKASZONYIFUNCTIONPROGRAM_ENUMS_H
