//
// Created by Dell on 2. 11. 2021.
//

#ifndef CUBICGRAPHKASZONYIFUNCTIONPROGRAM_ENUMS_H
#define CUBICGRAPHKASZONYIFUNCTIONPROGRAM_ENUMS_H

enum append{
    APPEND,
    NO_APPEND
};

enum suppression{
    PARALLEL,
    SEQUENTIAL
};

enum edgesFormat{
    MARK_ORIGINAL_EDGES,
    IGNORE_EDGE_ORIGINALITY
};

enum coloringAlgorithm{
    SAT,
    FACTOR,
    ANY
};

enum colorPrintFormat{
    COLORING_EXISTS,
    COLORING_NUMBER
};

enum formatType{
    RESISTANCE_VALUES,
    PARALLEL_PATH,
    SEQUENTIAL_PATH,
    KASZONYI_FUNCTION,
    NONE
};

#endif //CUBICGRAPHKASZONYIFUNCTIONPROGRAM_ENUMS_H
